language: rust
env:
  global:
    - secure: mItYdbN2lPVCRwIPmP+oL1jglgt3rIiHlF7EGnubwuIbQOv9fvXEoNBdX24Kwk4nTnFW1RPE7wPya3rqdVzBGj6KqFlFnlTnXHfdR7nribiOWNudL6DMf+h2BzyODacM+LVXlgTxNjDB9Sd6PscaQzbtPzBLVUvURNey1yWrtec=
install:
  - sudo apt-get install texinfo
script:
  - make build doc
notifications:
  email:
    - tophattedcoder@gmail.com
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh