[project]

name = "javascript"
version = "0.1"
readme = "README.md"
authors = ["Tom Bebbington <tophattedcoder@gmail.com>"]
tags = ["script"]

[[lib]]

name = "script"

[[bin]]

name = "interactive"

[[bin]]

name = "tests"
